# -*- coding: utf-8 -*-

import sys
sys.path.append('../core/')
from dataGroup import MyDataUnit

DATAPATH = 'path/to/testdata'

def generate_data():
    """
    Generally data is generated by a simulation software. There are a few options
    for using test data in order from best to worst:
        1. Generate data here rather than storing data in the repository
        Generating data make the project testing more portable
        2. using standard examples supplied from the vendor to generate data
        Instruct users to use these examples to generate data for testing
        3. Adding the data to a folder called testData
        Adding the data directly here would require it to be stored on the repo
        so that other developers can test. This is ineffcient use of space
    """
    pass

def test_dataUnit():
    """add tests here
    
    """
    DU = MyDataUnit(DATAPATH)
    # tests
    assert DU.some_function() == 'some function worked'

if __name__ == "__main__":
    
    test_dataUnit()